export const rActionTypes = {
    ADD_NEW_OPTIONS : 'ADD_NEW_OPTIONS',
    DELETE_OPTION : 'DELETE_OPTION',
    FETCHING_START:'FETCHING_START',
    FETCHING_ERROR:'FETCHING_ERROR',
    FETCHING_SUCCESS:'FETCHING_SUCCESS',
    CHANGE_OPTION_INPUT_NAME: 'CHANGE_OPTION_INPUT_NAME' ,
    ADD_CUSTOMFIELD: 'ADD_CUSTOMFIELD',
    DELETE_CUSTOMFIELD: 'DELETE_CUSTOMFIELD'
}