export const rActionTypes = {
    ADD_NEW_OPTIONS : 'ADD_NEW_OPTIONS',
    DELETE_OPTION : 'DELETE_OPTION',
    FETCHING_START:'FETCHING_START',
    FETCHING_ERROR:'FETCHING_ERROR',
    FETCHING_SUCCESS:'FETCHING_SUCCESS',
}